name: "Linting BPMN models"
description: "GitHub Action for automated linting of BPMN process models"
author: "Kristoffer Högberg"

inputs:
  bpmn-files-path:
    description: 'Location of your process models.'
    required: true
  custom-rules-folder:
    description: 'Location of your custom bpmnlint rules.'
    required: false

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: 'activity'
  color: 'green'
